import {build} from "esbuild";
import assert from "node:assert/strict";
import {fileURLToPath} from "node:url";
const app=fileURLToPath(new URL("../",import.meta.url));
const compiled=await build({stdin:{contents:'export {createDocumentStore} from "./src/document-store"; export {createNativeHandler} from "../preview/native-handler"; export {defaults,totalBalance} from "../lib/finance"; export {newEntryId} from "../lib/ids";',resolveDir:app,loader:"ts"},bundle:true,platform:"node",format:"esm",write:false,nodePaths:[app+"node_modules"]});
const {createDocumentStore,createNativeHandler,defaults,totalBalance,newEntryId}=await import('data:text/javascript;base64,'+Buffer.from(compiled.outputFiles[0].text).toString('base64'));
const saved=new Map();
let breakWrite=false,breakRead=false;
const store=createDocumentStore({list:async()=>[...saved.keys()],read:async name=>{if(breakRead)throw new Error("Leitura indisponível");return saved.get(name);},write:async(name,text)=>{if(breakWrite){saved.set(name,text.slice(0,15));throw new Error("Gravação interrompida");}saved.set(name,text);}});
const handler=createNativeHandler({...store,exportBackup:async()=>{}});
const post=(body)=>handler({method:"POST",body:JSON.stringify(body)});
assert.equal((await store.read()).revision,0);
const first=await post({action:"account",args:{name:"Banco",balance:100000},revision:0});
assert.equal(first.status,200);
assert.equal(totalBalance((await first.json()).data),100000);
const concurrent=await Promise.all([post({action:"account",args:{name:"Carteira",balance:5000},revision:1}),post({action:"account",args:{name:"Poupança",balance:3000},revision:1})]);
assert.deepEqual(concurrent.map(r=>r.status),[200,409]);
assert.equal((await store.read()).data.accounts.length,2);
breakWrite=true;
assert.equal((await post({action:"account",args:{name:"Teste",balance:1000},revision:2})).status,503);
breakWrite=false;
assert.equal((await store.read()).revision,2);
assert.equal(totalBalance((await store.read()).data),105000);
assert.equal((await post({action:"account",args:{name:"Teste",balance:1000},revision:2})).status,200);
assert.equal((await store.read()).revision,3);
assert.equal(totalBalance((await store.read()).data),106000);
breakRead=true;
assert.equal((await handler()).status,503);
breakRead=false;
assert.equal((await handler()).status,200);
assert.equal((await post({action:"account",args:{name:"Inválida",balance:0},revision:-1})).status,400);
assert.equal((await post({action:"restore",backup:{version:1,data:{...defaults(),accounts:[{id:"from-notebook",name:"Saldo do notebook",opening:25000}]}},revision:3})).status,200);
assert.equal(totalBalance((await store.read()).data),25000);
assert.equal((await post({action:"restore",backup:{version:1,data:{}},revision:4})).status,400);
assert.equal((await store.read()).revision,4);
for(const name of saved.keys())saved.set(name,"invalid-json");
assert.equal((await handler()).status,503);
assert.equal((await post({action:"account",args:{name:"Novo",balance:10},revision:0})).status,503);
assert.equal(saved.size,2);
const originalCrypto=globalThis.crypto;
const fallbackCrypto={getRandomValues:array=>originalCrypto.getRandomValues(array)};
Object.defineProperty(globalThis,"crypto",{value:fallbackCrypto,configurable:true});
assert.match(newEntryId(),/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/);
Object.defineProperty(globalThis,"crypto",{value:originalCrypto,configurable:true});
console.log("PASS: armazenamento nativo, recuperação de gravação interrompida, conflitos, erros de leitura, restauração de backup e IDs.");
