"use client";
import { useEffect, useRef, useState, type FormEvent, type ReactNode } from "react";
import { LayoutDashboard, ReceiptText, Wallet, CalendarDays, SlidersHorizontal, Plus, ChevronLeft, ChevronRight, Check, X, Pencil, RefreshCw, CircleAlert, Landmark, Repeat2, Download, ShieldCheck, Undo2, CheckCheck } from "lucide-react";
import { defaults, defaultThirteenth, receivables, today, shiftMonth, money, moneyInput, parseMoney, balance, totalBalance, instances, paydays, monthLabel, shortDate, holidays, dateParts, type Snapshot, type Account, type BillInstance, type Settings } from "../lib/finance";
import type { Action } from "../lib/actions";
import {nativeMode} from "../lib/native-port";
type View="overview"|"bills"|"accounts"|"calendar"|"settings";
type Modal={type:"account";account?:Account}|{type:"bill";bill?:BillInstance}|{type:"payment";bill:BillInstance}|{type:"income";payday:ReturnType<typeof paydays>[number]}|{type:"undo";id:string;label:string}|{type:"delete";bill:BillInstance}|{type:"install"};
type InstallEvent=Event & {prompt:()=>Promise<void>;userChoice:Promise<{outcome:string}>};
type ApiResult=Snapshot & {error?:string;snapshot?:Snapshot};
type WebContext={registerTool:(tool:{name:string;description:string;inputSchema:object;annotations?:object;execute:(input:unknown)=>unknown},options:{signal:AbortSignal})=>void|Promise<void>};
const localMode=()=>typeof window!=="undefined" && !!(window as Window & {openFinanceLocal?:boolean}).openFinanceLocal;
const mobileMode=()=>typeof window!=="undefined" && !!(window as Window & {openFinanceMobile?:boolean}).openFinanceMobile;
const asset=(path:string)=>typeof window!=="undefined"?((window as Window & {openFinanceAssets?:Record<string,string>}).openFinanceAssets?.[path]??path):path;
const nav=[{id:"overview",label:"Visão geral",icon:LayoutDashboard},{id:"bills",label:"Contas a pagar",icon:ReceiptText},{id:"accounts",label:"Meu dinheiro",icon:Wallet},{id:"calendar",label:"Calendário",icon:CalendarDays},{id:"settings",label:"Ajustes",icon:SlidersHorizontal}] as const;
const categories=["Moradia","Água e luz","Internet e telefone","Cartão de crédito","Saúde","Transporte","Outros"];
export default function FinanceApp() {
  const [view,setView]=useState<View>("overview"); const [month,setMonth]=useState(today().slice(0,7));
  const [snapshot,setSnapshot]=useState<Snapshot|null>(null); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false);
  const [error,setError]=useState(""); const [notice,setNotice]=useState(""); const [modal,setModal]=useState<Modal|null>(null); const [install,setInstall]=useState<InstallEvent|null>(null);
  const [offlineReady,setOfflineReady]=useState(false);
  const isLocal=localMode(); const data=snapshot?.data??defaults(); const now=today(); const all=instances(data,month); const pending=all.filter(b=>!b.payment); const paid=all.filter(b=>b.payment); const overdue=pending.filter(b=>b.due<now); const pendingTotal=pending.reduce((s,b)=>s+b.amount,0); const available=totalBalance(data); const payments=receivables(data,month);
  const planned=payments.filter(p=>!data.entries.some(e=>e.key===p.key)).reduce((sum,p)=>sum+p.amount,0);
  const [filter,setFilter]=useState("pending");
  async function load() { setLoading(true); try {const response=await fetch("/api/finance",{cache:"no-store"}); const result=await response.json() as ApiResult; if(!response.ok) throw new Error(result.error); setSnapshot(result);setError("");} catch(e) {setError((e as Error).message||"Não foi possível carregar. Tente novamente.");} finally {setLoading(false);} }
  useEffect(()=>{void load(); const handle=(event:Event)=>{event.preventDefault();setInstall(event as InstallEvent);};window.addEventListener("beforeinstallprompt",handle);if("serviceWorker" in navigator){if(mobileMode()&&(location.protocol==="https:"||["localhost","127.0.0.1"].includes(location.hostname)))void navigator.serviceWorker.register(new URL("sw.js",document.baseURI)).then(()=>navigator.serviceWorker.ready).then(()=>setOfflineReady(true)).catch(()=>{});else if(!localMode()&&!["localhost","127.0.0.1"].includes(location.hostname))void navigator.serviceWorker.register("/sw.js").catch(()=>{});}return()=>window.removeEventListener("beforeinstallprompt",handle);},[]);
  useEffect(()=>{const refresh=()=>{if(document.visibilityState==="visible"&&!modal&&!saving&&view!=="settings") void load();};window.addEventListener("focus",refresh);document.addEventListener("visibilitychange",refresh);return()=>{window.removeEventListener("focus",refresh);document.removeEventListener("visibilitychange",refresh);};},[modal,saving,view]);
  useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(""),4500);return()=>clearTimeout(t);},[notice]);
  useEffect(()=>{const context=(document as unknown as {modelContext?:WebContext}).modelContext;if(!context||!snapshot)return;const lifecycle=new AbortController();void Promise.resolve(context.registerTool({name:"consultar_financas",description:"Consulta os saldos, as contas a pagar e os recebimentos do mês no Open Finance.",inputSchema:{type:"object",properties:{mes:{type:"string",pattern:"^\\d{4}-(0[1-9]|1[0-2])$",description:"Mês no formato AAAA-MM"}},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){const value=input as {mes?:string};const selected=value?.mes??month;if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(selected))throw new Error("Mês inválido.");return {mes:selected,saldoEmCentavos:totalBalance(snapshot.data),contas:instances(snapshot.data,selected),recebimentos:receivables(snapshot.data,selected)};}},{signal:lifecycle.signal})).catch(()=>{});void Promise.resolve(context.registerTool({name:"abrir_cadastro_financeiro",description:"Abre o formulário para a pessoa cadastrar uma conta a pagar ou um saldo. O cadastro só é salvo após a confirmação no formulário.",inputSchema:{type:"object",properties:{tipo:{type:"string",enum:["conta_a_pagar","saldo"]}},required:["tipo"],additionalProperties:false},execute(input){const tipo=(input as {tipo?:string})?.tipo;if(tipo!=="conta_a_pagar"&&tipo!=="saldo")throw new Error("Tipo inválido.");setModal({type:tipo==="saldo"?"account":"bill"});return {formularioAberto:true};}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort();},[snapshot,month]);
  async function mutate(action:Action) {
    if(!snapshot||saving)return false;setSaving(true);setError("");
    try {const response=await fetch("/api/finance",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...action,revision:snapshot.revision})});const result=await response.json() as ApiResult;if(!response.ok){if(result.snapshot)setSnapshot(result.snapshot);throw new Error(result.error);}setSnapshot(result);setNotice("Registro salvo.");return true;}catch(e){setError((e as Error).message||"Falha ao salvar. Tente novamente.");return false;}finally{setSaving(false);}
  }
  function open(value:Modal) { setError("");setModal(value); }
  const enabled=!!snapshot&&!loading;
  const list=filter==="paid"?paid:filter==="overdue"?overdue:filter==="all"?all:pending;
  const next=receivables(data,now.slice(0,7)).concat(receivables(data,shiftMonth(now.slice(0,7),1))).sort((a,b)=>a.date.localeCompare(b.date)).find(p=>p.date>=now&&!data.entries.some(e=>e.key===p.key));
  const monthControl=<div className="month-control"><button className="icon-button" aria-label="Mês anterior" disabled={month<="2000-01"} onClick={()=>setMonth(shiftMonth(month,-1))}><ChevronLeft size={18}/></button><span>{monthLabel(month)}</span><button className="icon-button" aria-label="Próximo mês" disabled={month>="2100-12"} onClick={()=>setMonth(shiftMonth(month,1))}><ChevronRight size={18}/></button></div>;
  const billsSection=(compact=false)=><section className="panel bills-panel"><div className="section-heading"><div><h2>{compact?"Contas do mês":"Contas a pagar"}</h2><p>{pending.length} pendente{pending.length!==1?"s":""}{all.some(b=>b.due.slice(0,7)<month)?", incluindo meses anteriores":""}</p></div><button className="secondary" disabled={!enabled} onClick={()=>open({type:"bill"})}><Plus size={17}/>Nova conta</button></div><div className="filters" aria-label="Filtrar contas">{[["pending","Pendentes",pending.length],["overdue","Vencidas",overdue.length],["paid","Pagas",paid.length],["all","Todas",all.length]].map(([id,label,count])=><button key={id} aria-pressed={filter===id} onClick={()=>setFilter(String(id))}>{label}<span>{count}</span></button>)}</div>{!snapshot?<Empty icon={<ReceiptText/>} title={loading?"Carregando suas contas…":"Dados indisponíveis"} text="Seus registros aparecerão aqui."/>:!list.length?<Empty icon={<CheckCheck/>} title={data.bills.length?"Nenhuma conta neste filtro":"Cadastre sua primeira conta"} text={data.bills.length?"Escolha outro filtro ou mês para consultar.":"Informe o valor e o vencimento para acompanhar o que precisa pagar."}/>:<div className="bill-list"><div className="table-heading"><span>Conta</span><span>Vencimento</span><span>Valor</span><span>Situação</span><span/></div>{(compact?list.slice(0,6):list).map(b=><div className="bill-row" key={b.key}><div className="bill-name"><span className={`category-icon ${b.category==="Cartão de crédito"?"violet":""}`}><ReceiptText size={19}/></span><div><strong>{b.title}</strong><small>{b.category}{b.repeat==="monthly"?" · Mensal":""}</small></div></div><div className="bill-due"><span>{shortDate(b.due)}</span>{b.due.slice(0,7)<month&&<small>Mês anterior</small>}</div><strong className="bill-amount">{money(b.amount)}</strong><span className={`status ${b.payment?"paid":b.due<now?"late":b.due===now?"due-today":""}`}>{b.payment?"Paga":b.due<now?"Vencida":b.due===now?"Vence hoje":"Pendente"}</span><div className="row-actions">{b.payment?<button className="icon-button" aria-label={`Desfazer pagamento de ${b.title}`} onClick={()=>open({type:"undo",id:b.payment!.id,label:b.title})}><Undo2 size={17}/></button>:<><button className="pay-button" disabled={!enabled} onClick={()=>open({type:"payment",bill:b})}>Pagar</button><button className="icon-button" aria-label={`Editar ${b.title}`} onClick={()=>open({type:"bill",bill:b})}><Pencil size={16}/></button></>}</div></div>)}{compact&&list.length>6&&<button className="text-button more" onClick={()=>setView("bills")}>Ver as {list.length} contas</button>}</div>}</section>;
  const incomeSection=<section className="panel income-panel"><div className="section-heading"><div><h2>Seus recebimentos</h2><p>{payments.length} entradas previstas em {monthLabel(month)}</p></div><button className="icon-button" aria-label="Configurar recebimentos" onClick={()=>setView("settings")}><SlidersHorizontal size={19}/></button></div><div className="payday-cards">{payments.map((p,i)=>{const entry=data.entries.find(e=>e.key===p.key);return <div className={`payday ${entry?"received":""}`} key={p.key}><div className="payday-top"><span className="payday-rule">{p.rule}</span><span className="payday-number">0{i+1}</span></div><h3>{shortDate(p.date)}<small>{new Intl.DateTimeFormat("pt-BR",{weekday:"long",timeZone:"UTC"}).format(new Date(p.date+"T12:00:00Z"))}</small></h3><div className="payday-bottom"><div><span>{p.label}</span><strong>{p.amount||entry?money(entry?.amount??p.amount):"Definir valor"}</strong></div>{entry?<button className="received-button" onClick={()=>open({type:"undo",id:entry.id,label:p.label})}><Check size={16}/>Recebido</button>:<button className="secondary" disabled={!enabled} onClick={()=>p.amount?open({type:"income",payday:p}):setView("settings")}>{p.amount?"Registrar":"Configurar"}</button>}</div></div>;})}</div><p className="note"><ShieldCheck size={16}/>A entrada só soma ao saldo quando você registra o recebimento.</p></section>;
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><img src={asset("/favicon.svg")} alt=""/><span>open<span>finance</span></span></div><p className="nav-label">SEU CONTROLE</p><nav>{nav.map(n=><button key={n.id} className={view===n.id?"active":""} onClick={()=>setView(n.id)}><n.icon size={20}/><span>{n.label}</span>{n.id==="bills"&&overdue.length>0&&<b>{overdue.length}</b>}</button>)}</nav><div className="sidebar-bottom"><div className="location-card"><CalendarDays size={18}/><div><strong>Jacareí, SP</strong><small>{data.settings.saturday?"Sábado conta como dia útil":"Dias úteis: segunda a sexta"}</small></div></div>{!isLocal&&<button className="install-sidebar" onClick={()=>open({type:"install"})}><Download size={18}/>Instalar aplicativo</button>}</div></aside><main className="workspace"><header className="topbar"><div className="mobile-brand"><img src={asset("/favicon.svg")} alt=""/>Open Finance</div><div className="breadcrumbs">Meu controle financeiro <span>/ {nav.find(n=>n.id===view)?.label}</span></div><div className="sync"><ShieldCheck size={16}/><span>{saving?"Salvando…":loading?"Carregando…":snapshot?"Dados salvos":"Sem conexão"}</span><button className="icon-button" title="Atualizar dados" aria-label="Atualizar dados" disabled={loading||saving||!!modal} onClick={()=>void load()}><RefreshCw size={16} className={loading?"spin":""}/></button></div></header><div className="page-content"><div className="page-heading"><div><h1>{view==="overview"?"Visão geral":nav.find(n=>n.id===view)?.label}</h1></div>{view!=="settings"&&monthControl}</div>{error&&!modal&&<div className="error-banner" role="alert"><CircleAlert size={20}/><span>{error}</span>{!snapshot&&<button onClick={()=>void load()}>Tentar novamente</button>}</div>}{notice&&<div className="toast" role="status"><Check size={18}/>{notice}</div>}
  {(view==="overview"||view==="bills")&&<><div className="metrics"><section className="metric balance-card"><div className="metric-label"><span>Quanto tenho agora</span><Wallet size={21}/></div><strong>{snapshot?money(available):"…"}</strong><div className="metric-footer"><span>{data.accounts.length} conta{data.accounts.length!==1?"s":""} cadastrada{data.accounts.length!==1?"s":""}</span><button disabled={!enabled} onClick={()=>open({type:"account"})}><Plus size={16}/>Adicionar saldo</button></div></section><section className="metric"><div className="metric-label"><span>Contas pendentes</span><ReceiptText size={20}/></div><strong>{snapshot?money(pendingTotal):"…"}</strong><p>{pending.length} conta{pending.length!==1?"s":""} para pagar{overdue.length>0&&<span className="red"> · {overdue.length} vencida{overdue.length!==1?"s":""}</span>}</p></section><section className="metric"><div className="metric-label"><span>Após pagar as pendências</span><Landmark size={20}/></div><strong className={available-pendingTotal<0?"red":""}>{snapshot?money(available-pendingTotal):"…"}</strong><p>Com entradas previstas: <b>{money(available-pendingTotal+planned)}</b></p></section></div>{view==="overview"&& !data.accounts.length&&snapshot&&<div className="setup-strip"><div><strong>Comece pelo dinheiro que você já tem.</strong><p>Cadastre o saldo da sua conta bancária ou carteira.</p></div><button className="primary" onClick={()=>open({type:"account"})}><Plus size={18}/>Cadastrar saldo</button></div>}{view==="overview"&&incomeSection}{billsSection(view==="overview")}{view==="overview"&&<div className="overview-bottom"><section className="panel"><div className="section-heading"><div><h2>Onde está seu dinheiro</h2></div><button className="text-button" onClick={()=>setView("accounts")}>Ver contas</button></div>{!data.accounts.length?<p className="muted small-empty">Você ainda não cadastrou um saldo.</p>:data.accounts.map(a=><div className="account-line" key={a.id}><div><Landmark size={19}/>{a.name}</div><strong>{money(balance(a,data))}</strong></div>)}</section><section className="next-payment"><CalendarDays size={24}/><div><span>Próximo recebimento previsto</span><h3>{next?`${shortDate(next.date)} · ${next.rule}`:"Recebimentos registrados"}</h3><p>{next?.amount?money(next.amount):"Configure os valores em Ajustes."}</p></div></section></div>}</>}
  {view==="accounts"&&<><div className="section-heading"><p className="muted">Saldos atuais das suas contas e do dinheiro em mãos.</p><button className="primary" disabled={!enabled} onClick={()=>open({type:"account"})}><Plus size={18}/>Adicionar conta</button></div><div className="accounts-grid">{data.accounts.map(a=><section className="panel account-card" key={a.id}><div className="section-heading"><span className="account-symbol"><Landmark/></span><button className="icon-button" aria-label={`Ajustar saldo de ${a.name}`} onClick={()=>open({type:"account",account:a})}><Pencil size={18}/></button></div><h2>{a.name}</h2><strong className={balance(a,data)<0?"red":""}>{money(balance(a,data))}</strong><p>Saldo disponível</p></section>)}</div>{!data.accounts.length&&<section className="panel"><Empty icon={<Wallet/>} title="Seu dinheiro começa aqui" text="Adicione uma conta bancária ou carteira com o saldo que você tem hoje."/></section>}<section className="panel history"><div className="section-heading"><div><h2>Movimentações registradas</h2><p>Recebimentos, pagamentos e ajustes de saldo</p></div></div>{!data.entries.length?<p className="muted small-empty">Nenhuma movimentação registrada.</p>:data.entries.slice().reverse().map(e=><div className="history-row" key={e.id}><div><strong>{e.label}</strong><small>{shortDate(e.date)} · {data.accounts.find(a=>a.id===e.accountId)?.name}</small></div><strong className={e.amount>0?"green":""}>{e.amount>0?"+":""}{money(e.amount)}</strong>{e.kind!=="adjustment"&&<button className="icon-button" aria-label={`Desfazer ${e.label}`} onClick={()=>open({type:"undo",id:e.id,label:e.label})}><Undo2 size={17}/></button>}</div>)}</section></>}
  {view==="calendar"&&<><Calendar month={month} data={data} all={all}/>{incomeSection}<section className="panel"><div className="section-heading"><h2>Feriados de {month.slice(0,4)}</h2><span className="muted">Jacareí/SP</span></div><div className="holiday-grid">{holidays(Number(month.slice(0,4))).map((h,i)=><div key={i}><strong>{shortDate(h.date)}</strong><span>{h.name}</span></div>)}</div><p className="note">Pontos facultativos não são descontados automaticamente. Você pode acrescentar datas em Ajustes.</p></section></>}
  {(mobileMode()&&view==="overview")&&<section className="setup-strip"><div><strong>Open Finance no celular</strong><p>{offlineReady?"Pronto para usar sem internet neste aparelho.":"A primeira abertura precisa de internet para preparar o uso offline."}</p><p>Os registros ficam neste aparelho. Use o backup para levar dados do notebook.</p></div><button className="primary" onClick={()=>open({type:"install"})}><Download size={18}/>Instalar no celular</button></section>}
  {view==="settings"&&snapshot&&<SettingsPanel settings={data.settings} saving={saving} submit={mutate} local={isLocal} installApp={!isLocal||mobileMode()?()=>open({type:"install"}):undefined}/>}
  <footer className="footer">Open Finance<span>{nativeMode()?"Dados neste aplicativo · Jacareí/SP":isLocal?"Dados neste navegador · Jacareí/SP":"Controle pessoal · Jacareí/SP"}</span></footer></div></main><nav className="mobile-nav" aria-label="Navegação principal">{nav.map(n=><button key={n.id} className={view===n.id?"active":""} onClick={()=>setView(n.id)}><n.icon size={21}/><span>{n.id==="bills"?"Contas":n.id==="accounts"?"Saldos":n.id==="overview"?"Resumo":n.label}</span></button>)}</nav>
  {modal&&<Dialog title={modal.type==="account"?(modal.account?"Ajustar saldo":"Adicionar meu dinheiro"):modal.type==="bill"?(modal.bill?"Editar conta":"Nova conta a pagar"):modal.type==="payment"?"Registrar pagamento":modal.type==="income"?"Registrar recebimento":modal.type==="install"?"Instalar Open Finance":modal.type==="delete"?"Excluir conta":"Desfazer lançamento"} close={()=>!saving&&setModal(null)}>{error&&<div className="form-error" role="alert">{error}</div>}<ModalForm key={modal.type+("bill" in modal?modal.bill?.key??"":"")} modal={modal} accounts={data.accounts} data={data} month={month} saving={saving} install={install} run={mutate} close={()=>setModal(null)} fail={setError} switchModal={open}/></Dialog>}
  </div>;
}
function Empty({icon,title,text}:{icon:ReactNode;title:string;text:string}) { return <div className="empty"><div>{icon}</div><h3>{title}</h3><p>{text}</p></div>; }
function Dialog({title,close,children}:{title:string;close:()=>void;children:ReactNode}) { const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();return()=>ref.current?.close();},[]);return <dialog ref={ref} onCancel={e=>{e.preventDefault();close();}} onClick={e=>{if(e.target===ref.current)close();}} className="dialog" aria-labelledby="dialog-title"><div className="dialog-heading"><h2 id="dialog-title">{title}</h2><button className="icon-button" aria-label="Fechar" onClick={close}><X size={21}/></button></div>{children}</dialog>; }
function ModalForm({modal,accounts,data,month,saving,install,run,close,fail,switchModal}:{modal:Modal;accounts:Account[];data:Snapshot["data"];month:string;saving:boolean;install:InstallEvent|null;run:(a:Action)=>Promise<boolean>;close:()=>void;fail:(m:string)=>void;switchModal:(m:Modal)=>void}) {
  async function submit(e:FormEvent<HTMLFormElement>) {e.preventDefault();const f=new FormData(e.currentTarget);try {let action:Action;
    if(modal.type==="account")action={action:"account",args:{id:modal.account?.id,name:String(f.get("name")),balance:parseMoney(String(f.get("amount")))}};
    else if(modal.type==="bill")action={action:"bill",args:{id:modal.bill?.id,title:String(f.get("name")),amount:parseMoney(String(f.get("amount"))),date:String(f.get("date")),repeat:f.get("repeat") as "once"|"monthly",category:String(f.get("category"))}};
    else if(modal.type==="payment")action={action:"payment",args:{key:modal.bill.key,month,accountId:String(f.get("accountId")),date:String(f.get("date"))}};
    else if(modal.type==="income")action={action:"income",args:{key:modal.payday.key,month,accountId:String(f.get("accountId")),date:String(f.get("date")),amount:parseMoney(String(f.get("amount")))}};
    else if(modal.type==="undo")action={action:"undo",args:{id:modal.id}};
    else if(modal.type==="delete")action={action:"deleteBill",args:{id:modal.bill.id}};
    else return;
    if(await run(action))close();
  }catch(error){fail((error as Error).message);} }
  if(modal.type==="install")return <div className="install-content"><img src={asset("/icons/icon-192.png")} alt="Open Finance"/><p>{mobileMode()?"Abra o endereço HTTPS deste aplicativo no navegador do celular. Depois da instalação, abra pelo ícone na tela inicial.":"Acesse o mesmo endereço e entre na mesma conta nos seus dispositivos."}</p>{install&&<button className="primary" onClick={async()=>{await install.prompt();await install.userChoice;close();}}>Instalar aplicativo</button>}<div><h3>No iPhone</h3><p>No Safari, abra o menu da página, toque em Compartilhar e escolha “Adicionar à Tela de Início”. Ative “Abrir como App da Web”, se essa opção aparecer, e toque em Adicionar.</p></div><div><h3>No Android</h3><p>No Chrome, abra o menu de três pontos e procure “Instalar e criar atalho” ou “Adicionar à tela inicial”. Confirme em Instalar.</p></div><p className="note">{mobileMode()?"Após preparar o uso offline, você pode consultar e salvar sem internet. Os dados ficam neste aparelho. Para levar registros entre notebook e celular, use Baixar backup e Restaurar backup em Ajustes.":"É necessário estar conectado à internet para consultar e salvar os registros."}</p></div>;
  if((modal.type==="payment"||modal.type==="income")&&!accounts.length)return <div className="no-account"><p>Cadastre uma conta ou carteira para indicar onde o dinheiro entra ou sai.</p><button className="primary" onClick={()=>switchModal({type:"account"})}>Cadastrar saldo</button></div>;
  return <form onSubmit={submit} className="form"><fieldset disabled={saving}>
    {modal.type==="account"&&<><label>Nome da conta ou carteira<input name="name" maxLength={80} required autoFocus placeholder="Ex.: Conta bancária, dinheiro em mãos" defaultValue={modal.account?.name}/></label><label>Saldo que tenho hoje (R$)<input name="amount" inputMode="decimal" required placeholder="0,00" defaultValue={modal.account?moneyInput(balance(modal.account,data)):""}/></label><p className="note">{modal.account?"A diferença será registrada como ajuste de saldo, preservando suas movimentações.":"Informe apenas o dinheiro disponível agora. Os próximos salários são configurados em Ajustes."}</p></>}
    {modal.type==="bill"&&<><label>Nome da conta<input name="name" maxLength={80} required autoFocus placeholder="Ex.: Energia, aluguel, cartão" defaultValue={modal.bill?.title}/></label><div className="form-grid"><label>Valor (R$)<input name="amount" inputMode="decimal" required placeholder="0,00" defaultValue={modal.bill?moneyInput(modal.bill.amount):""}/></label><label>Vencimento<input name="date" type="date" required min="2000-01-01" max="2100-12-31" defaultValue={modal.bill?.date??(month===today().slice(0,7)?today():month+"-01")}/></label></div><label>Categoria<select name="category" defaultValue={modal.bill?.category??"Outros"}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Repetição<select name="repeat" defaultValue={modal.bill?.repeat??"once"}><option value="once">Somente esta vez</option><option value="monthly">Todo mês, no mesmo dia</option></select></label><p className="note">{modal.bill?"Alterações de valor valem para as contas ainda pendentes. Os pagamentos já registrados são preservados.":"Contas mensais aparecem a partir do vencimento informado. Meses curtos usam o último dia do mês."}</p></>}
    {(modal.type==="payment"||modal.type==="income")&&<><div className="transaction-summary"><span>{modal.type==="payment"?modal.bill.title:modal.payday.label}</span><strong>{money(modal.type==="payment"?modal.bill.amount:modal.payday.amount)}</strong><small>{modal.type==="payment"?`Vencimento: ${shortDate(modal.bill.due)}`:`Previsão: ${shortDate(modal.payday.date)}`}</small></div><label>{modal.type==="payment"?"Pagar com":"Receber em"}<select name="accountId" required>{accounts.map(a=><option key={a.id} value={a.id}>{a.name} ({money(balance(a,data))})</option>)}</select></label>{modal.type==="income"&&<label>Valor recebido (R$)<input name="amount" inputMode="decimal" required defaultValue={moneyInput(modal.payday.amount)}/></label>}<label>{modal.type==="payment"?"Data do pagamento":"Data do recebimento"}<input name="date" type="date" required min="2000-01-01" max={today()} defaultValue={today()}/></label><p className="note">{modal.type==="payment"?"O valor será descontado do saldo da conta escolhida.":"O valor será acrescentado ao saldo da conta escolhida."}</p></>}
    {modal.type==="undo"&&<p>Desfazer “{modal.label}” restaura o saldo anterior e deixa o pagamento ou recebimento pendente novamente.</p>}
    {modal.type==="delete"&&<p>Excluir “{modal.bill.title}” remove essa conta e suas próximas repetições. Contas com pagamentos registrados são preservadas.</p>}
    <div className="form-actions">{modal.type==="bill"&&modal.bill&&!data.entries.some(e=>e.key?.startsWith(`bill:${modal.bill!.id}:`))&&<button className="danger-text" type="button" onClick={()=>switchModal({type:"delete",bill:modal.bill!})}>Excluir</button>}<button type="button" className="secondary" onClick={close}>Cancelar</button><button className={modal.type==="delete"?"primary danger":"primary"} type="submit">{saving?"Salvando…":modal.type==="payment"?"Confirmar pagamento":modal.type==="income"?"Confirmar recebimento":modal.type==="undo"?"Desfazer":modal.type==="delete"?"Excluir conta":"Salvar"}</button></div>
  </fieldset></form>;
}
function SettingsPanel({settings,saving,submit,local,installApp}:{settings:Settings;saving:boolean;submit:(a:Action)=>Promise<boolean>;local:boolean;installApp?:()=>void}) {
  const [error,setError]=useState(""); const thirteenth=settings.thirteenth??defaultThirteenth();
  const months=["Janeiro","Fevereiro","Março","Abril","Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro","Dezembro"];
  async function save(e:FormEvent<HTMLFormElement>) {
    e.preventDefault(); const f=new FormData(e.currentTarget);
    try {
      setError("");
      await submit({action:"settings",args:{
        fifthAmount:parseMoney(String(f.get("fifth"))),twentiethAmount:parseMoney(String(f.get("twentieth"))),
        saturday:f.get("saturday")==="on",twentiethRule:f.get("twentiethRule") as Settings["twentiethRule"],
        extraHolidays:String(f.get("holidays")).split(/[\n,;]+/).map(s=>s.trim()).filter(Boolean),
        thirteenth:{enabled:f.get("thirteenthEnabled")==="on",firstAmount:parseMoney(String(f.get("thirteenthFirst"))),secondAmount:parseMoney(String(f.get("thirteenthSecond"))),firstMonth:Number(f.get("firstMonth")),firstDay:Number(f.get("firstDay")),secondMonth:Number(f.get("secondMonth")),secondDay:Number(f.get("secondDay")),rule:f.get("thirteenthRule") as "exact"|"previous"},
      }});
    } catch(err) {setError((err as Error).message);}
  }
  return <form className="panel settings-panel form" onSubmit={save}><fieldset disabled={saving}>
    <div className="section-heading"><div><h2>Pagamentos e calendário</h2><p>Configure os valores que você recebe em cada data.</p></div></div>
    {error&&<div role="alert" className="form-error">{error}</div>}
    <div className="form-grid"><label>Recebo no 5º dia útil (R$)<input name="fifth" inputMode="decimal" required defaultValue={moneyInput(settings.fifthAmount)}/></label><label>Recebo no dia 20 (R$)<input name="twentieth" inputMode="decimal" required defaultValue={moneyInput(settings.twentiethAmount)}/></label></div>
    <div className="settings-divider"/><h3>13º salário</h3>
    <label className="checkbox-label"><input type="checkbox" name="thirteenthEnabled" defaultChecked={thirteenth.enabled}/>Incluir as duas parcelas do 13º na previsão anual</label>
    <p className="note">Primeira parcela em novembro e segunda em dezembro. As datas abaixo se repetem a cada ano; ajuste ao calendário da sua empresa.</p>
    <h4>1ª parcela · Adiantamento</h4>
    <label>Valor líquido da 1ª parcela (R$)<input name="thirteenthFirst" inputMode="decimal" required defaultValue={moneyInput(thirteenth.firstAmount)}/></label>
    <div className="form-grid"><label>Mês da 1ª parcela<select name="firstMonth" defaultValue={thirteenth.firstMonth}>{months.map((m,i)=><option key={m} value={i+1}>{m}</option>)}</select></label><label>Dia da 1ª parcela<input name="firstDay" type="number" min="1" max="31" required defaultValue={thirteenth.firstDay}/></label></div>
    <h4>2ª parcela · Complemento</h4>
    <label>Valor líquido da 2ª parcela (R$)<input name="thirteenthSecond" inputMode="decimal" required defaultValue={moneyInput(thirteenth.secondAmount)}/></label>
    <div className="form-grid"><label>Mês da 2ª parcela<select name="secondMonth" defaultValue={thirteenth.secondMonth}>{months.map((m,i)=><option key={m} value={i+1}>{m}</option>)}</select></label><label>Dia da 2ª parcela<input name="secondDay" type="number" min="1" max="31" required defaultValue={thirteenth.secondDay}/></label></div>
    <label>Quando a data do 13º cai em fim de semana ou feriado<select name="thirteenthRule" defaultValue={thirteenth.rule}><option value="exact">Manter a data informada</option><option value="previous">Antecipar para o dia bancário anterior</option></select></label>
    <p className="note">Informe o valor que deve cair na conta, já com descontos. As parcelas podem ter valores diferentes. Em meses curtos, um dia inexistente usa o último dia do mês. O saldo só aumenta após registrar o recebimento.</p>
    <p className="note">Prazos legais: primeira parcela até 30/11 e segunda até 20/12. A primeira corresponde, em regra, à metade do salário; o complemento pode ter INSS e IRRF. <a href="https://www.planalto.gov.br/ccivil_03/leis/l4749.htm" target="_blank" rel="noreferrer">Lei 4.749/1965</a> · <a href="https://www.gov.br/esocial/pt-br/noticias/como-pagar-a-primeira-parcela-do-13o-salario" target="_blank" rel="noreferrer">Orientação do eSocial</a>.</p>
    <div className="settings-divider"/><h3>5º dia útil</h3>
    <label className="checkbox-label"><input type="checkbox" name="saturday" defaultChecked={settings.saturday}/>Contar sábado como dia útil</label><p className="note">Domingos e feriados de Jacareí/SP são descontados. Pontos facultativos ficam fora da regra automática.</p>
    <label>Quando o dia 20 cai em fim de semana ou feriado<select name="twentiethRule" defaultValue={settings.twentiethRule}><option value="exact">Manter o dia 20</option><option value="previous">Antecipar para o dia bancário anterior</option><option value="next">Usar o próximo dia bancário</option></select></label>
    <label>Dias adicionais sem expediente<textarea name="holidays" rows={3} placeholder="Uma data por linha: 2026-12-24" defaultValue={settings.extraHolidays.join("\n")}/></label><p className="note">Use o formato AAAA-MM-DD. As datas adicionais valem apenas para o ano informado. Até 15 datas.</p>
    {local&&<><div className="settings-divider"/><h3>Backup dos registros</h3><p className="note">Guarde uma cópia antes de trocar de aparelho ou reinstalar o aplicativo.</p><div className="backup-actions"><button type="button" className="secondary" onClick={async()=>{try{await (window as any).openFinanceBackup.export();}catch(e){setError((e as Error).message);}}}>{nativeMode()?"Salvar backup":"Baixar backup"}</button><label className="secondary backup-upload">Restaurar backup<input type="file" accept="application/json,.json" onChange={async e=>{const file=e.currentTarget.files?.[0];e.currentTarget.value="";if(file)try{await (window as any).openFinanceBackup.import(file);}catch(error){setError((error as Error).message);}}}/></label></div></>}
    {installApp&&<><div className="settings-divider"/><h3>Aplicativo no celular</h3><button type="button" className="secondary" onClick={installApp}><Download size={18}/>Instalar no celular</button></>}
    <div className="settings-divider"/><h3>Seu acesso</h3><p className="muted">{local?(nativeMode()?"Os registros ficam no armazenamento deste aplicativo. Ele funciona sem internet. Salve backups para levar os dados entre aparelhos; esta versão não sincroniza automaticamente.":mobileMode()?"Os registros ficam neste aparelho. Abra sempre pelo mesmo ícone. Use backups para transferir os dados entre aparelhos; esta versão não sincroniza automaticamente.":"Os registros ficam neste navegador, neste dispositivo. Abra sempre este mesmo arquivo pelo mesmo navegador. A versão local não sincroniza dados com outros aparelhos."):"Os registros são salvos na sua conta. Use a mesma conta ao entrar no notebook e no celular."}</p><p className="note">Cadastro manual de valores. O aplicativo não conecta com bancos nem realiza pagamentos.</p><button className="primary" type="submit">{saving?"Salvando…":"Salvar ajustes"}</button>
  </fieldset></form>;
}
function Calendar({month,data,all}:{month:string;data:Snapshot["data"];all:BillInstance[]}) {const [y,m]=dateParts(month);const offset=(new Date(Date.UTC(y,m-1,1)).getUTCDay()+6)%7;const days=new Date(Date.UTC(y,m,0)).getUTCDate();const pd=receivables(data,month);const hs=holidays(y);return <section className="panel calendar-panel"><div className="calendar-legend"><span><i className="legend-income"/>Recebimento</span><span><i className="legend-bill"/>Conta pendente</span><span><i className="legend-holiday"/>Feriado</span></div><div className="calendar-grid">{["SEG","TER","QUA","QUI","SEX","SÁB","DOM"].map(d=><div className="weekday" key={d}>{d}</div>)}{Array.from({length:offset},(_,i)=><div className="calendar-day blank" key={`empty${i}`}/>)}{Array.from({length:days},(_,i)=>{const date=`${month}-${String(i+1).padStart(2,"0")}`;const bills=all.filter(b=>b.due===date&&!b.payment);const pay=pd.filter(p=>p.date===date);const holiday=hs.find(h=>h.date===date);return <div key={date} className={`calendar-day ${date===today()?"today":""}`}><strong>{i+1}</strong>{pay.map(p=><span key={p.key} className="calendar-event income-event" title={p.label}>{p.rule}</span>)}{bills.length>0&&<span className="calendar-event bill-event" title={bills.map(b=>b.title).join(", ")}>{bills.length} conta{bills.length>1?"s":""}</span>}{holiday&&<span className="calendar-event holiday-event" title={holiday.name}>Feriado</span>}</div>;})}</div><div className="calendar-details"><h3>Agenda do mês</h3>{[...pd.map(p=>({date:p.date,label:`${p.label} (${p.rule})`,amount:p.amount,kind:"income"})),...all.filter(b=>b.due.slice(0,7)===month).map(b=>({date:b.due,label:b.title+(b.payment?" · Paga":""),amount:b.amount,kind:"bill"}))].sort((a,b)=>a.date.localeCompare(b.date)).map((e,i)=><div key={i}><strong>{shortDate(e.date)}</strong><span>{e.label}</span><b className={e.kind==="income"?"green":""}>{money(e.amount)}</b></div>)}</div></section>; }



